title = 'TWON API'
version = '0.0.1'
docs_path = './docs'

trust_origins = [
    'http://localhost:5173',
    'http://localhost:8000',
    'https://replyrift.xciv.de'
]

[logging]
agent_path = './logs/agents'
