title = 'TWON API'
version = '0.0.1'
docs_path = './docs'

trust_origins = [
    'http://localhost:5173',
    'http://localhost:8000',
]

[agents]
persona_src_path = './data/personas'
prompt_src_path = './data/prompts'
log_path = './api/logs/responses'
